-- Skyball lightweight leaderboard schema for Supabase/Postgres.
-- Run once in the Supabase SQL editor, then add the project URL and anon key
-- to GitHub Actions as VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY secrets.

create extension if not exists pgcrypto;

create table if not exists public.players (
  id uuid primary key default gen_random_uuid(),
  public_player_id uuid not null unique,
  display_name varchar(12) not null check (display_name ~ '^[A-Za-z0-9][A-Za-z0-9 _.-]{1,10}[A-Za-z0-9]$'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.runs (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  total_time_ms integer not null check (total_time_ms between 20000 and 7200000),
  level_splits jsonb not null,
  completed_at timestamptz not null default now(),
  game_version varchar(20) not null,
  validation_status varchar(10) not null default 'flagged' check (validation_status in ('valid', 'flagged', 'rejected'))
);

create index if not exists runs_valid_time_idx on public.runs (validation_status, total_time_ms, completed_at);
create index if not exists runs_player_idx on public.runs (player_id, total_time_ms);

alter table public.players enable row level security;
alter table public.runs enable row level security;

revoke all on public.players, public.runs from anon, authenticated;

create or replace function public.skyball_safe_name(value text)
returns text
language sql
immutable
as $$
  select upper(left(regexp_replace(trim(coalesce(value, '')), '[^A-Za-z0-9 _.-]', '', 'g'), 12));
$$;

create or replace function public.submit_skyball_run(
  p_public_player_id uuid,
  p_display_name text,
  p_total_time_ms integer,
  p_level_splits jsonb,
  p_game_version text
)
returns table(validation_status text, all_time_rank bigint, monthly_rank bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player_id uuid;
  v_name text := public.skyball_safe_name(p_display_name);
  v_split_count integer;
  v_split_sum bigint;
  v_status text := 'valid';
  v_recent_count integer;
begin
  if length(v_name) < 3 or length(v_name) > 12 or v_name !~ '^[A-Z0-9][A-Z0-9 _.-]{1,10}[A-Z0-9]$' then
    raise exception 'Invalid display name';
  end if;

  if p_game_version is null or length(p_game_version) > 20 then
    raise exception 'Invalid game version';
  end if;

  if jsonb_typeof(p_level_splits) <> 'array' then
    raise exception 'Level splits must be an array';
  end if;

  select count(*), coalesce(sum((value #>> '{}')::bigint), 0)
    into v_split_count, v_split_sum
  from jsonb_array_elements(p_level_splits)
  where jsonb_typeof(value) = 'number';

  if v_split_count <> 20
     or exists (select 1 from jsonb_array_elements(p_level_splits) value where (value #>> '{}')::numeric < 400 or (value #>> '{}')::numeric > 1800000)
     or p_total_time_ms < 20000
     or p_total_time_ms > 7200000
     or abs(v_split_sum - p_total_time_ms) > 1500 then
    v_status := 'rejected';
  end if;

  insert into public.players(public_player_id, display_name)
  values (p_public_player_id, v_name)
  on conflict (public_player_id) do update
    set display_name = excluded.display_name, updated_at = now()
  returning id into v_player_id;

  select count(*) into v_recent_count
  from public.runs
  where player_id = v_player_id and completed_at > now() - interval '1 minute';

  if v_recent_count >= 5 and v_status = 'valid' then v_status := 'flagged'; end if;

  insert into public.runs(player_id, total_time_ms, level_splits, game_version, validation_status)
  values (v_player_id, p_total_time_ms, p_level_splits, p_game_version, v_status);

  if v_status <> 'valid' then
    return query select v_status, null::bigint, null::bigint;
    return;
  end if;

  return query
  with all_best as (
    select player_id, min(total_time_ms) best_time
    from public.runs r where r.validation_status = 'valid' group by player_id
  ), month_best as (
    select player_id, min(total_time_ms) best_time
    from public.runs r
    where r.validation_status = 'valid' and r.completed_at >= date_trunc('month', now())
    group by player_id
  )
  select v_status,
    (select count(*) + 1 from all_best where best_time < (select best_time from all_best where player_id = v_player_id)),
    (select count(*) + 1 from month_best where best_time < (select best_time from month_best where player_id = v_player_id));
end;
$$;

create or replace function public.get_skyball_leaderboard(
  p_period text default 'monthly',
  p_offset integer default 0,
  p_limit integer default 50
)
returns table(rank bigint, public_player_id uuid, display_name text, total_time_ms integer, completed_at timestamptz)
language sql
stable
security definer
set search_path = public
as $$
  with eligible as (
    select r.*, row_number() over (partition by r.player_id order by r.total_time_ms, r.completed_at) player_row
    from public.runs r
    where r.validation_status = 'valid'
      and (p_period <> 'monthly' or r.completed_at >= date_trunc('month', now()))
      and (p_period <> 'monthly' or r.completed_at < date_trunc('month', now()) + interval '1 month')
  ), ranked as (
    select row_number() over (order by e.total_time_ms, e.completed_at) rank,
      p.public_player_id, p.display_name::text, e.total_time_ms, e.completed_at
    from eligible e join public.players p on p.id = e.player_id
    where e.player_row = 1
  )
  select * from ranked order by rank offset greatest(p_offset, 0) limit least(greatest(p_limit, 1), 50);
$$;

create or replace function public.get_skyball_personal_best(p_public_player_id uuid)
returns table(total_time_ms integer, level_splits jsonb, completed_at timestamptz, all_time_rank bigint, monthly_rank bigint)
language sql
stable
security definer
set search_path = public
as $$
  with target as (
    select r.* from public.runs r join public.players p on p.id = r.player_id
    where p.public_player_id = p_public_player_id and r.validation_status = 'valid'
    order by r.total_time_ms, r.completed_at limit 1
  ), month_target as (
    select r.* from public.runs r join public.players p on p.id = r.player_id
    where p.public_player_id = p_public_player_id and r.validation_status = 'valid'
      and r.completed_at >= date_trunc('month', now())
      and r.completed_at < date_trunc('month', now()) + interval '1 month'
    order by r.total_time_ms, r.completed_at limit 1
  ), all_best as (
    select r.player_id, min(r.total_time_ms) best_time from public.runs r where r.validation_status = 'valid' group by r.player_id
  ), month_best as (
    select r.player_id, min(r.total_time_ms) best_time from public.runs r
    where r.validation_status = 'valid' and r.completed_at >= date_trunc('month', now()) group by r.player_id
  )
  select t.total_time_ms, t.level_splits, t.completed_at,
    (select count(*) + 1 from all_best where best_time < t.total_time_ms),
    (select count(*) + 1 from month_best where best_time < (select total_time_ms from month_target))
  from target t;
$$;

create or replace function public.update_skyball_player_name(p_public_player_id uuid, p_display_name text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_name text := public.skyball_safe_name(p_display_name);
begin
  if length(v_name) < 3 or length(v_name) > 12 or v_name !~ '^[A-Z0-9][A-Z0-9 _.-]{1,10}[A-Z0-9]$' then
    raise exception 'Invalid display name';
  end if;
  update public.players p set display_name = v_name, updated_at = now() where p.public_player_id = p_public_player_id;
end;
$$;

revoke all on function public.submit_skyball_run(uuid, text, integer, jsonb, text) from public;
revoke all on function public.get_skyball_leaderboard(text, integer, integer) from public;
revoke all on function public.get_skyball_personal_best(uuid) from public;
revoke all on function public.update_skyball_player_name(uuid, text) from public;

grant execute on function public.submit_skyball_run(uuid, text, integer, jsonb, text) to anon, authenticated;
grant execute on function public.get_skyball_leaderboard(text, integer, integer) to anon, authenticated;
grant execute on function public.get_skyball_personal_best(uuid) to anon, authenticated;
grant execute on function public.update_skyball_player_name(uuid, text) to anon, authenticated;
